# Generated by Django 4.2.7 on 2025-07-22 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productview'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='remote_image_url',
            field=models.URLField(blank=True, help_text='Optional: Use an online image URL if no local image is uploaded.', null=True),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/'),
        ),
    ]
