# Generated by Django 4.2.7 on 2025-07-20 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='preferences',
            field=models.CharField(blank=True, choices=[('fashion', 'Sustainable Fashion'), ('home', 'Eco Home & Garden'), ('tech', 'Green Technology'), ('food', 'Organic Food'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
