# Generated by Django 4.2.7 on 2025-07-20 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_userprofile_preferences'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_phone_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone_verification_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
